import { createApp, onMounted } from 'vue'
import * as THREE from 'three'
import { GLTFLoader } from 'three/examples/jsm/loaders/GLTFLoader.js'
import { DRACOLoader } from 'three/examples/jsm/loaders/DRACOLoader.js'
import gsap from 'gsap'
import { ScrollTrigger } from 'gsap/ScrollTrigger'
import Lenis from 'lenis'
import './styles-clean.css'

gsap.registerPlugin(ScrollTrigger)
const MODEL_URL='models/stonegate_web_light_draco.glb'
const VIDEO_URL='media/portal-world.mp4'

const App={template:`<main class="site-shell"><section class="hero-sequence" id="hero"><div class="world-portal"><video id="worldVideo" class="world-video" muted playsinline loop preload="auto"></video></div><canvas id="gateCanvas" class="gate-canvas"></canvas><header class="top-nav"><a class="brand"><strong>伴山</strong><span>BANSHAN</span></a><nav><a href="#local">本地向导</a><a href="#voice">AI语音向导</a><a href="#discover">城市探索</a></nav></header><div class="hero-copy copy-a"><p>BANSHAN PORTAL</p><h1>穿过山门<br/>进入城市的另一面</h1><span>视频是 DOM 背景，只通过门洞遮罩露出。</span></div><div class="hero-copy copy-b"><p>CAMERA FLY THROUGH</p><h2>靠近山门。</h2><span>石门和门洞一起放大，模拟镜头推进。</span></div><div class="hero-copy copy-c"><p>HIDDEN WORLD</p><h2>云海世界展开。</h2><span>穿过后，视频扩展成完整画面。</span></div><aside class="chapter"><i></i><b id="chapterNumber">01</b><em id="chapterName">GATEWAY</em></aside><div class="scroll-hint"><i></i><span>SCROLL TO ENTER</span></div></section><section class="content-section layered-copy" id="discover"><div class="copy-stage"><p class="section-kicker">EXPERIENCE FIRST</p><div class="copy-step"><h2>官网不是功能说明书，而是伴山的第一段体验。</h2><p>首屏先建立进入另一个世界的感受。</p></div><div class="copy-step"><h2>先让用户产生探索欲，再承接业务功能。</h2><p>本地向导、AI 语音向导和城市探索成为下一步。</p></div><div class="copy-step"><h2>每一次滚动，都像镜头继续向前。</h2><p>文字、卡片、图片和遮罩跟随滚动分层变化。</p></div></div></section><section class="content-section parallax-feature"><div class="mask-image"></div><div class="feature-copy"><p class="section-kicker">LOCAL GUIDE</p><h2>把目的地变成真实的人、路线和故事。</h2><p>伴山连接本地向导、城市体验者和抵达城市的人。</p></div></section><section class="drag-section" id="local"><div class="drag-head"><p class="section-kicker">DRAG TO NAVIGATE</p><h2>城市体验不是列表，而是一组可以横向探索的场景。</h2></div><div class="drag-viewport" id="dragViewport"><div class="drag-track" id="dragTrack"><article><span>01</span><h3>山野疗愈</h3><p>清晨、云海、山路和本地向导。</p></article><article><span>02</span><h3>城市漫游</h3><p>从街区、咖啡馆、老店和故事开始。</p></article><article id="voice"><span>03</span><h3>AI语音向导</h3><p>实时对话，边走边听，边问边发现。</p></article><article><span>04</span><h3>商务陪同</h3><p>陌生城市里的高效接待和路线协助。</p></article></div></div></section></main>`,setup(){onMounted(()=>{smooth();video();gateScene();heroScroll();sections();dragCards()})}}
createApp(App).mount('#app')

function smooth(){const lenis=new Lenis({lerp:.075,wheelMultiplier:.82,smoothWheel:true});lenis.on('scroll',ScrollTrigger.update);gsap.ticker.add(t=>lenis.raf(t*1000));gsap.ticker.lagSmoothing(0)}
function video(){const v=document.getElementById('worldVideo');v.src=VIDEO_URL;v.playbackRate=.58;v.addEventListener('loadedmetadata',()=>{v.currentTime=.01;v.play().catch(()=>{})},{once:true});v.play().catch(()=>{})}
function gateScene(){const canvas=document.getElementById('gateCanvas'),renderer=new THREE.WebGLRenderer({canvas,alpha:true,antialias:true,powerPreference:'high-performance'});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.setSize(innerWidth,innerHeight);renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.02;const scene=new THREE.Scene(),camera=new THREE.PerspectiveCamera(35,innerWidth/innerHeight,.1,120);camera.position.set(0,.06,7.2);const gate=new THREE.Group();gate.position.set(0,-.38,0);scene.add(gate);loadGate(gate);scene.add(lights());window.gateRig={gate,camera};function loop(){camera.lookAt(0,0,0);renderer.render(scene,camera);requestAnimationFrame(loop)}loop();addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight)})}
function heroScroll(){const root=document.documentElement,num=document.getElementById('chapterNumber'),name=document.getElementById('chapterName'),state={p:0,chapter:''};gsap.to(state,{p:1,ease:'none',scrollTrigger:{trigger:'.hero-sequence',start:'top top',end:'bottom bottom',scrub:1.05},onUpdate:()=>{const p=state.p,approach=smoothstep(0,.30,p),pass=smoothstep(.30,.55,p),reveal=smoothstep(.55,.75,p),settle=smoothstep(.75,1,p);root.style.setProperty('--hero-progress',p.toFixed(3));root.style.setProperty('--portal-w',`${lerp(15.5,100,reveal)}vw`);root.style.setProperty('--portal-h',`${lerp(56,100,reveal)}vh`);root.style.setProperty('--portal-radius-top',`${lerp(46,0,reveal)}%`);root.style.setProperty('--portal-radius-bottom',`${lerp(4,0,reveal)}%`);root.style.setProperty('--video-scale',lerp(1.20,1.04,reveal).toFixed(3));root.style.setProperty('--video-y',`${lerp(-2,-6,settle)}vh`);const rig=window.gateRig;if(rig?.gate){rig.gate.scale.setScalar(lerp(1,1.45,approach)+pass*1.95);rig.gate.position.x=lerp(0,-1.35,pass);rig.gate.position.y=lerp(-.38,-.18,approach);rig.gate.rotation.y=THREE.MathUtils.degToRad(lerp(0,-16,pass));rig.gate.traverse(n=>{if(n.material){n.material.opacity=1-smoothstep(.58,.72,p);n.material.needsUpdate=true}})}setChapter(p<.30?'01':p<.65?'02':'03',p<.30?'GATEWAY':p<.65?'ENTER':'WORLD')}});function setChapter(n,l){const k=n+l;if(state.chapter===k)return;state.chapter=k;num.textContent=n;name.textContent=l}}
function loadGate(group){const draco=new DRACOLoader();draco.setDecoderPath('https://www.gstatic.com/draco/versioned/decoders/1.5.7/');const loader=new GLTFLoader();loader.setDRACOLoader(draco);loader.load(MODEL_URL,gltf=>{const model=gltf.scene;normalize(model,6.05);model.traverse(n=>{if(n.isMesh){n.frustumCulled=false;n.material=rock(n.material)}});group.add(model)})}
function lights(){const g=new THREE.Group();g.add(new THREE.HemisphereLight(0xffdfbe,0x050505,.82));const key=new THREE.DirectionalLight(0xffb16b,4.6);key.position.set(1.8,3.4,2.4);g.add(key);const fill=new THREE.DirectionalLight(0x9fb2c0,.42);fill.position.set(-2,1.3,3);g.add(fill);return g}
function rock(src){const mat=new THREE.MeshStandardMaterial({color:0x72563b,roughness:.92,metalness:0,transparent:true,opacity:1});if(src?.map)mat.map=src.map;if(src?.normalMap)mat.normalMap=src.normalMap;return mat}
function normalize(model,target){const box=new THREE.Box3().setFromObject(model),size=new THREE.Vector3(),center=new THREE.Vector3();box.getSize(size);box.getCenter(center);model.position.sub(center);model.scale.setScalar(target/Math.max(size.x,size.y,size.z))}
function sections(){const steps=gsap.utils.toArray('.copy-step');gsap.set(steps.slice(1),{opacity:0,y:34,filter:'blur(18px)'});const tl=gsap.timeline({scrollTrigger:{trigger:'.layered-copy',start:'top top',end:'+=220%',scrub:1,pin:true}});steps.forEach((s,i)=>{if(!i)return;tl.to(steps[i-1],{opacity:0,y:-34,filter:'blur(18px)'},i-.15).to(s,{opacity:1,y:0,filter:'blur(0px)'},i)})}
function dragCards(){const v=document.getElementById('dragViewport'),t=document.getElementById('dragTrack');if(!v||!t)return;let down=false,start=0,base=0,x=0,target=0,max=0;const measure=()=>max=Math.max(0,t.scrollWidth-v.clientWidth);const tick=()=>{x+=(target-x)*.12;t.style.transform=`translate3d(${x}px,0,0)`;requestAnimationFrame(tick)};measure();tick();addEventListener('resize',measure);v.onpointerdown=e=>{down=true;start=e.clientX;base=target;v.setPointerCapture(e.pointerId)};v.onpointermove=e=>{if(down)target=clamp(base+e.clientX-start,-max,0)};v.onpointerup=()=>down=false}
function lerp(a,b,t){return a+(b-a)*t}function clamp(v,min,max){return Math.max(min,Math.min(max,v))}function smoothstep(a,b,v){const x=clamp((v-a)/(b-a),0,1);return x*x*(3-2*x)}
